/**
 ******************************************************************************
 * Xenia : Xbox 360 Emulator Research Project                                 *
 ******************************************************************************
 * Copyright 2026 Ben Vanik. All rights reserved.                             *
 * Released under the BSD license - see LICENSE in the root for more details. *
 ******************************************************************************
 */

#import "xenia/ui/ios_compat_data.h"

#include <cstdint>

// Autogenerated by `xb premake`.
#include "build/version.h"

#ifndef XE_BUILD_VERSION
#define XE_BUILD_VERSION "1.0.0"
#endif

#ifndef XE_BUILD_NUMBER
#define XE_BUILD_NUMBER "0"
#endif

#ifndef XE_BUILD_COMMIT_SHORT
#define XE_BUILD_COMMIT_SHORT ""
#endif

#import "xenia/ui/ios_theme.h"

NSString* const kXeniaCompatDataDidUpdateNotification = @"XeniaCompatDataDidUpdateNotification";
NSString* const kXeniaDiscussionDidUpdateNotification = @"XeniaDiscussionDidUpdateNotification";

UIColor* xe_compat_status_color(NSString* status) {
  if ([status isEqualToString:@"playable"])
    return [UIColor colorWithRed:0x34 / 255.0 green:0xd3 / 255.0 blue:0x99 / 255.0 alpha:1.0];
  if ([status isEqualToString:@"ingame"])
    return [UIColor colorWithRed:0x60 / 255.0 green:0xa5 / 255.0 blue:0xfa / 255.0 alpha:1.0];
  if ([status isEqualToString:@"intro"])
    return [UIColor colorWithRed:0xfb / 255.0 green:0xbf / 255.0 blue:0x24 / 255.0 alpha:1.0];
  if ([status isEqualToString:@"loads"])
    return [UIColor colorWithRed:0xfb / 255.0 green:0x92 / 255.0 blue:0x3c / 255.0 alpha:1.0];
  if ([status isEqualToString:@"nothing"])
    return [UIColor colorWithRed:0xf8 / 255.0 green:0x71 / 255.0 blue:0x71 / 255.0 alpha:1.0];
  if ([status isEqualToString:@"untested"]) {
    return [XeniaTheme textMuted];
  }
  return [XeniaTheme textMuted];
}

NSString* xe_compat_status_label(NSString* status) {
  if ([status isEqualToString:@"playable"]) return @"Playable";
  if ([status isEqualToString:@"ingame"]) return @"In-Game";
  if ([status isEqualToString:@"intro"]) return @"Intro";
  if ([status isEqualToString:@"loads"]) return @"Loads";
  if ([status isEqualToString:@"nothing"]) return @"Nothing";
  if ([status isEqualToString:@"untested"]) return @"Untested";
  return @"Unknown";
}

UIColor* xe_compat_perf_color(NSString* perf) {
  if ([perf isEqualToString:@"great"]) {
    return [XeniaTheme accent];
  }
  if ([perf isEqualToString:@"ok"]) {
    return [UIColor colorWithRed:0x60 / 255.0 green:0xa5 / 255.0 blue:0xfa / 255.0 alpha:1.0];
  }
  if ([perf isEqualToString:@"poor"]) {
    return [XeniaTheme statusWarning];
  }
  return [XeniaTheme textMuted];
}

NSString* xe_compat_perf_label(NSString* perf) {
  if ([perf isEqualToString:@"great"]) return @"Great";
  if ([perf isEqualToString:@"ok"]) return @"Okay";
  if ([perf isEqualToString:@"poor"]) return @"Poor";
  if ([perf isEqualToString:@"n/a"]) return @"N/A";
  return @"Unknown";
}

NSString* xe_format_iso_date(NSString* iso) {
  if (!iso || iso.length < 10) {
    return iso ?: @"";
  }
  static NSDateFormatter* parser = nil;
  static NSDateFormatter* date_only_parser = nil;
  static NSDateFormatter* formatter = nil;
  static dispatch_once_t once;
  dispatch_once(&once, ^{
    parser = [[NSDateFormatter alloc] init];
    parser.dateFormat = @"yyyy-MM-dd'T'HH:mm:ss";
    parser.locale = [[[NSLocale alloc] initWithLocaleIdentifier:@"en_US_POSIX"] autorelease];
    date_only_parser = [[NSDateFormatter alloc] init];
    date_only_parser.dateFormat = @"yyyy-MM-dd";
    date_only_parser.locale =
        [[[NSLocale alloc] initWithLocaleIdentifier:@"en_US_POSIX"] autorelease];
    formatter = [[NSDateFormatter alloc] init];
    formatter.dateStyle = NSDateFormatterMediumStyle;
    formatter.timeStyle = NSDateFormatterNoStyle;
  });

  NSString* trimmed = [iso substringToIndex:MIN(iso.length, (NSUInteger)19)];
  NSDate* date = [parser dateFromString:trimmed];
  if (!date) {
    date = [date_only_parser dateFromString:[iso substringToIndex:MIN(iso.length, (NSUInteger)10)]];
  }
  return date ? [formatter stringFromDate:date]
              : [iso substringToIndex:MIN(iso.length, (NSUInteger)10)];
}

NSString* xe_platform_display_text(NSString* platform, NSString* os_version) {
  if (![platform isKindOfClass:[NSString class]] || platform.length == 0) {
    return @"";
  }
  NSString* platform_name = [platform isEqualToString:@"ios"]     ? @"iOS"
                            : [platform isEqualToString:@"macos"] ? @"macOS"
                                                                  : platform;
  if (![os_version isKindOfClass:[NSString class]] || os_version.length == 0) {
    return platform_name;
  }
  return [NSString stringWithFormat:@"%@ %@", platform_name, os_version];
}

NSString* xe_string_from_object(id value) {
  return [value isKindOfClass:[NSString class]] ? (NSString*)value : nil;
}

NSDictionary* xe_dictionary_from_object(id value) {
  return [value isKindOfClass:[NSDictionary class]] ? (NSDictionary*)value : nil;
}

BOOL xe_compat_entry_has_summary_fields(NSDictionary* entry) {
  if (!entry) {
    return NO;
  }
  return xe_string_from_object(entry[@"status"]).length > 0 ||
         xe_string_from_object(entry[@"perf"]).length > 0 ||
         xe_string_from_object(entry[@"notes"]).length > 0;
}

NSDictionary* xe_compat_summary_named(NSDictionary* compat_info, NSString* key) {
  NSDictionary* summaries = xe_dictionary_from_object(compat_info[@"summaries"]);
  NSDictionary* summary = summaries ? xe_dictionary_from_object(summaries[key]) : nil;
  return xe_compat_entry_has_summary_fields(summary) ? summary : nil;
}

NSDictionary* xe_release_summary_from_compat_info(NSDictionary* compat_info) {
  return xe_compat_summary_named(compat_info, @"release");
}

NSInteger xe_compat_status_rank(NSString* status) {
  if ([status isEqualToString:@"playable"]) return 4;
  if ([status isEqualToString:@"ingame"]) return 3;
  if ([status isEqualToString:@"intro"]) return 2;
  if ([status isEqualToString:@"loads"]) return 1;
  return 0;
}

NSString* xe_compat_build_fingerprint(NSDictionary* build_info) {
  if (!build_info) {
    return nil;
  }
  NSArray<NSString*>* fields = @[
    xe_string_from_object(build_info[@"buildId"]) ?: @"",
    xe_string_from_object(build_info[@"appVersion"]) ?: @"",
    xe_string_from_object(build_info[@"buildNumber"]) ?: @"",
    xe_string_from_object(build_info[@"stage"]) ?: @"",
    xe_string_from_object(build_info[@"commitShort"]) ?: @"",
  ];
  NSMutableArray<NSString*>* parts = [NSMutableArray arrayWithCapacity:fields.count];
  for (NSString* field in fields) {
    if (field.length > 0) {
      [parts addObject:[field lowercaseString]];
    }
  }
  if (parts.count == 0) {
    return nil;
  }
  return [parts componentsJoinedByString:@"|"];
}

BOOL xe_compat_date_is_newer(NSString* candidate, NSString* baseline) {
  if (candidate.length == 0) {
    return NO;
  }
  if (baseline.length == 0) {
    return YES;
  }
  return [candidate compare:baseline options:NSCaseInsensitiveSearch] == NSOrderedDescending;
}

NSDictionary* xe_compat_newest_report(NSArray<NSDictionary*>* reports) {
  NSDictionary* newest = nil;
  NSString* newest_date = @"";
  NSInteger newest_rank = -1;
  for (NSDictionary* report in reports) {
    NSString* date = xe_string_from_object(report[@"date"]) ?: @"";
    NSString* status = xe_string_from_object(report[@"status"]) ?: @"";
    NSInteger rank = xe_compat_status_rank(status);
    if (!newest || xe_compat_date_is_newer(date, newest_date) ||
        ([date isEqualToString:newest_date] && rank > newest_rank)) {
      newest = report;
      newest_date = date;
      newest_rank = rank;
    }
  }
  return newest;
}

NSDictionary* xe_compat_best_report(NSArray<NSDictionary*>* reports) {
  NSDictionary* best = nil;
  NSInteger best_rank = -1;
  NSString* best_date = @"";
  for (NSDictionary* report in reports) {
    NSString* status = xe_string_from_object(report[@"status"]) ?: @"";
    NSInteger rank = xe_compat_status_rank(status);
    NSString* date = xe_string_from_object(report[@"date"]) ?: @"";
    if (!best || rank > best_rank ||
        (rank == best_rank && xe_compat_date_is_newer(date, best_date))) {
      best = report;
      best_rank = rank;
      best_date = date;
    }
  }
  return best;
}

BOOL xe_compat_report_affects_release(NSDictionary* report) {
  NSDictionary* build_info = xe_dictionary_from_object(report[@"build"]);
  NSString* channel = xe_string_from_object(build_info[@"channel"]);
  NSNumber* official = [build_info[@"official"] isKindOfClass:[NSNumber class]]
                           ? (NSNumber*)build_info[@"official"]
                           : nil;
  if ([channel isEqualToString:@"preview"]) {
    return NO;
  }
  if ([channel isEqualToString:@"self-built"]) {
    return NO;
  }
  if (official && !official.boolValue) {
    return NO;
  }
  return YES;
}

NSArray<NSDictionary*>* xe_compat_release_evidence_reports(NSDictionary* compat_info,
                                                           NSString* platform) {
  NSArray* reports = [compat_info[@"reports"] isKindOfClass:[NSArray class]]
                         ? (NSArray*)compat_info[@"reports"]
                         : nil;
  if (!reports || reports.count == 0) {
    return nil;
  }

  NSMutableArray<NSDictionary*>* release_like_reports = [NSMutableArray array];
  for (id raw_report in reports) {
    NSDictionary* report = xe_dictionary_from_object(raw_report);
    if (!report) {
      continue;
    }
    NSString* report_platform = xe_string_from_object(report[@"platform"]);
    if (platform.length > 0 && ![report_platform isEqualToString:platform]) {
      continue;
    }
    if (xe_compat_report_affects_release(report)) {
      [release_like_reports addObject:report];
    }
  }

  if (release_like_reports.count == 0) {
    return nil;
  }

  NSMutableDictionary<NSString*, NSMutableArray<NSDictionary*>*>* explicit_release_groups =
      [NSMutableDictionary dictionary];
  for (NSDictionary* report in release_like_reports) {
    NSDictionary* build_info = xe_dictionary_from_object(report[@"build"]);
    NSString* channel = xe_string_from_object(build_info[@"channel"]);
    NSNumber* official = [build_info[@"official"] isKindOfClass:[NSNumber class]]
                             ? (NSNumber*)build_info[@"official"]
                             : nil;
    NSString* fingerprint = xe_compat_build_fingerprint(build_info);
    if (![channel isEqualToString:@"release"] || (official && !official.boolValue) ||
        fingerprint.length == 0) {
      continue;
    }
    NSMutableArray<NSDictionary*>* group = explicit_release_groups[fingerprint];
    if (!group) {
      group = [NSMutableArray array];
      explicit_release_groups[fingerprint] = group;
    }
    [group addObject:report];
  }

  if (explicit_release_groups.count > 0) {
    NSArray<NSDictionary*>* newest_group = nil;
    NSString* newest_group_date = @"";
    for (NSArray<NSDictionary*>* group in [explicit_release_groups allValues]) {
      NSDictionary* newest_report = xe_compat_newest_report(group);
      NSString* newest_date = xe_string_from_object(newest_report[@"date"]) ?: @"";
      if (!newest_group || xe_compat_date_is_newer(newest_date, newest_group_date)) {
        newest_group = group;
        newest_group_date = newest_date;
      }
    }
    return newest_group;
  }

  NSMutableArray<NSDictionary*>* legacy_release_reports = [NSMutableArray array];
  for (NSDictionary* report in release_like_reports) {
    if (!xe_dictionary_from_object(report[@"build"])) {
      [legacy_release_reports addObject:report];
    }
  }
  return legacy_release_reports.count > 0 ? legacy_release_reports : nil;
}

NSString* xe_derive_public_release_status(NSArray<NSDictionary*>* reports) {
  if (reports.count == 0) {
    return @"untested";
  }
  NSString* best_status = @"nothing";
  NSInteger best_rank = 0;
  BOOL has_non_playable = NO;
  for (NSDictionary* report in reports) {
    NSString* status = xe_string_from_object(report[@"status"]) ?: @"nothing";
    NSInteger rank = xe_compat_status_rank(status);
    if (rank > best_rank) {
      best_rank = rank;
      best_status = status;
    }
    if (![status isEqualToString:@"playable"]) {
      has_non_playable = YES;
    }
  }
  if ([best_status isEqualToString:@"playable"] && has_non_playable) {
    return @"ingame";
  }
  return best_status;
}

NSString* xe_derive_public_release_perf(NSArray<NSDictionary*>* reports, NSString* status) {
  if (reports.count == 0 || [status isEqualToString:@"untested"] ||
      [status isEqualToString:@"nothing"]) {
    return @"n/a";
  }
  BOOL has_ok = NO;
  BOOL has_great = NO;
  for (NSDictionary* report in reports) {
    NSString* perf = xe_string_from_object(report[@"perf"]);
    if ([perf isEqualToString:@"poor"]) {
      return @"poor";
    }
    if ([perf isEqualToString:@"ok"]) {
      has_ok = YES;
    } else if ([perf isEqualToString:@"great"]) {
      has_great = YES;
    }
  }
  if (has_ok) {
    return @"ok";
  }
  if (has_great) {
    return @"great";
  }
  return @"n/a";
}

NSDictionary* xe_ios_public_release_summary_from_compat_info(NSDictionary* compat_info) {
  // Match the website's compatibility table for iOS:
  // 1. Consider only iOS reports that affect the public release verdict.
  //    Preview and self-built reports are excluded, while legacy reports with
  //    no build metadata still count as release-track evidence.
  // 2. If explicit official release-build reports exist, use only the newest
  //    matching build group; otherwise fall back to legacy release-track reports.
  // 3. Derive the public status from the best release-track report, but
  //    downgrade Playable to In-Game when mixed release outcomes exist so the
  //    badge stays conservative, just like the site.
  // 4. Derive perf conservatively from the same release-track evidence, with
  //    any Poor report forcing the public perf tier to Poor.
  //
  // TODO(reality): Re-evaluate this mirror logic periodically against xenios.jp
  // so the app stays aligned if the website changes its release-summary rules.
  // Ideally this derivation should move into the GitHub Actions worker so the
  // website and app consume the same published verdict instead of mirroring
  // logic in two places.
  NSArray<NSDictionary*>* reports = xe_compat_release_evidence_reports(compat_info, @"ios");
  if (!reports || reports.count == 0) {
    return nil;
  }

  NSString* status = xe_derive_public_release_status(reports);
  NSString* perf = xe_derive_public_release_perf(reports, status);
  NSDictionary* newest_report = xe_compat_newest_report(reports);
  NSDictionary* best_report = xe_compat_best_report(reports);
  NSDictionary* detail_report = best_report ?: newest_report;

  NSMutableDictionary* summary = [NSMutableDictionary dictionary];
  summary[@"status"] = status;
  summary[@"perf"] = perf;
  summary[@"reportCount"] = @(reports.count);

  NSString* updated_at = xe_string_from_object(newest_report[@"date"]);
  if (updated_at.length > 0) {
    summary[@"updatedAt"] = updated_at;
    summary[@"date"] = updated_at;
  }

  NSString* notes = xe_string_from_object(newest_report[@"notes"]);
  if (notes.length > 0) {
    summary[@"notes"] = notes;
  }

  if (detail_report) {
    for (NSString* key in @[ @"device", @"platform", @"osVersion", @"arch", @"gpuBackend" ]) {
      NSString* value = xe_string_from_object(detail_report[key]);
      if (value.length > 0) {
        summary[key] = value;
      }
    }
    NSDictionary* build_info = xe_dictionary_from_object(newest_report[@"build"]);
    if (build_info) {
      summary[@"build"] = build_info;
    }
  }

  return summary;
}

NSDictionary* xe_preferred_summary_from_compat_info(NSDictionary* compat_info) {
  NSDictionary* ios_public_release = xe_ios_public_release_summary_from_compat_info(compat_info);
  if (ios_public_release) {
    return ios_public_release;
  }
  NSDictionary* release = xe_release_summary_from_compat_info(compat_info);
  if (release) {
    return release;
  }
  if (xe_compat_entry_has_summary_fields(compat_info)) {
    return compat_info;
  }
  NSDictionary* all = xe_compat_summary_named(compat_info, @"all");
  if (all) {
    return all;
  }
  return xe_compat_summary_named(compat_info, @"preview");
}

UIColor* xe_compat_channel_color(NSString* channel) {
  if ([channel isEqualToString:@"release"]) {
    return [UIColor colorWithRed:0x34 / 255.0 green:0xd3 / 255.0 blue:0x99 / 255.0 alpha:1.0];
  }
  if ([channel isEqualToString:@"preview"]) {
    return [UIColor colorWithRed:0x60 / 255.0 green:0xa5 / 255.0 blue:0xfa / 255.0 alpha:1.0];
  }
  return [XeniaTheme textMuted];
}

NSString* xe_compat_channel_label(NSString* channel) {
  if ([channel isEqualToString:@"release"]) return @"Release";
  if ([channel isEqualToString:@"preview"]) return @"Preview";
  if ([channel isEqualToString:@"self-built"]) return @"Self-Built";
  return @"Unknown";
}

NSString* xe_release_stage_display_label(NSString* stage) {
  if ([stage isEqualToString:@"alpha"]) return @"Alpha";
  if ([stage isEqualToString:@"beta"]) return @"Beta";
  if ([stage isEqualToString:@"rc"]) return @"RC";
  return nil;
}

NSString* xe_build_version_label(NSDictionary* build_info) {
  NSString* app_version = xe_string_from_object(build_info[@"appVersion"]);
  NSString* build_number = xe_string_from_object(build_info[@"buildNumber"]);
  if (app_version.length > 0 && build_number.length > 0) {
    return [NSString stringWithFormat:@"%@-%@", app_version, build_number];
  }
  if (app_version.length > 0) {
    return app_version;
  }
  return nil;
}

NSString* xe_compat_build_label(NSDictionary* build_info) {
  NSString* channel = xe_string_from_object(build_info[@"channel"]);
  NSString* commit_short = xe_string_from_object(build_info[@"commitShort"]);
  if ([channel isEqualToString:@"self-built"] && commit_short.length > 0) {
    return commit_short;
  }

  NSString* version_label = xe_build_version_label(build_info);
  if (version_label.length > 0) {
    return version_label;
  }
  NSString* build_number = xe_string_from_object(build_info[@"buildNumber"]);
  if (build_number.length > 0) {
    return [NSString stringWithFormat:@"Build %@", build_number];
  }
  NSString* build_id = xe_string_from_object(build_info[@"buildId"]);
  return build_id.length > 0 ? build_id : nil;
}

NSString* xe_user_facing_build_label(NSDictionary* build_info) {
  if (!build_info) {
    return @"Unknown Build";
  }

  NSString* channel = xe_string_from_object(build_info[@"channel"]);
  NSString* stage_label =
      xe_release_stage_display_label(xe_string_from_object(build_info[@"stage"]));
  NSString* version_label = xe_build_version_label(build_info);
  NSString* commit_short = xe_string_from_object(build_info[@"commitShort"]);

  if ([channel isEqualToString:@"preview"] && version_label.length > 0) {
    if (stage_label.length > 0) {
      return [NSString stringWithFormat:@"%@ Preview %@", stage_label, version_label];
    }
    return [NSString stringWithFormat:@"Preview %@", version_label];
  }
  if ([channel isEqualToString:@"release"] && version_label.length > 0) {
    if (stage_label.length > 0) {
      return [NSString stringWithFormat:@"%@ %@", stage_label, version_label];
    }
    return version_label;
  }
  if (commit_short.length > 0) {
    return [NSString stringWithFormat:@"Dev build %@", commit_short];
  }
  if (version_label.length > 0) {
    return [NSString stringWithFormat:@"Build %@", version_label];
  }

  NSString* build_number = xe_string_from_object(build_info[@"buildNumber"]);
  if (build_number.length > 0) {
    return [NSString stringWithFormat:@"Build %@", build_number];
  }

  NSString* build_id = xe_string_from_object(build_info[@"buildId"]);
  return build_id.length > 0 ? [NSString stringWithFormat:@"Build %@", build_id] : @"Unknown Build";
}

NSString* xe_sanitize_build_component(NSString* value) {
  if (![value isKindOfClass:[NSString class]] || value.length == 0) {
    return @"unknown";
  }
  NSMutableString* sanitized = [NSMutableString stringWithCapacity:value.length];
  NSCharacterSet* alnum = [NSCharacterSet alphanumericCharacterSet];
  BOOL last_was_dash = NO;
  NSString* lower = [value lowercaseString];
  for (NSUInteger i = 0; i < lower.length; ++i) {
    unichar c = [lower characterAtIndex:i];
    if ([alnum characterIsMember:c]) {
      [sanitized appendFormat:@"%C", c];
      last_was_dash = NO;
    } else if (!last_was_dash) {
      [sanitized appendString:@"-"];
      last_was_dash = YES;
    }
  }
  while ([sanitized hasPrefix:@"-"]) {
    [sanitized deleteCharactersInRange:NSMakeRange(0, 1)];
  }
  while ([sanitized hasSuffix:@"-"]) {
    [sanitized deleteCharactersInRange:NSMakeRange(sanitized.length - 1, 1)];
  }
  return sanitized.length > 0 ? sanitized : @"unknown";
}

NSString* xe_make_build_id(NSString* platform, NSString* channel, NSString* app_version,
                           NSString* build_number, NSString* stage) {
  NSString* base = [NSString stringWithFormat:@"%@-%@-%@-%@", xe_sanitize_build_component(platform),
                                              xe_sanitize_build_component(channel),
                                              xe_sanitize_build_component(app_version),
                                              xe_sanitize_build_component(build_number)];
  if ([stage isKindOfClass:[NSString class]] && stage.length > 0 &&
      ![stage isEqualToString:@"stable"]) {
    return [base stringByAppendingFormat:@"-%@", xe_sanitize_build_component(stage)];
  }
  return base;
}

NSDictionary* xe_compat_build_info_from_entry(NSDictionary* entry) {
  if (!entry) {
    return nil;
  }
  NSDictionary* nested = xe_dictionary_from_object(entry[@"build"]);
  NSString* build_id = xe_string_from_object(nested ? nested[@"buildId"] : entry[@"buildId"]);
  NSString* channel = xe_string_from_object(nested ? nested[@"channel"] : entry[@"channel"]);
  id official_value = nested ? nested[@"official"] : entry[@"official"];
  NSNumber* official =
      [official_value isKindOfClass:[NSNumber class]] ? (NSNumber*)official_value : nil;
  NSString* app_version =
      xe_string_from_object(nested ? nested[@"appVersion"] : entry[@"appVersion"]);
  NSString* build_number =
      xe_string_from_object(nested ? nested[@"buildNumber"] : entry[@"buildNumber"]);
  NSString* commit_short =
      xe_string_from_object(nested ? nested[@"commitShort"] : entry[@"commitShort"]);
  NSString* stage = xe_string_from_object(nested ? nested[@"stage"] : entry[@"stage"]);
  if (build_id.length == 0 && channel.length == 0 && app_version.length == 0 &&
      build_number.length == 0 && commit_short.length == 0 && stage.length == 0 && !official) {
    return nil;
  }

  NSMutableDictionary* build = [NSMutableDictionary dictionary];
  if (build_id.length > 0) {
    build[@"buildId"] = build_id;
  }
  if (channel.length > 0) {
    build[@"channel"] = channel;
  }
  if (official) {
    build[@"official"] = official;
  }
  if (app_version.length > 0) {
    build[@"appVersion"] = app_version;
  }
  if (build_number.length > 0) {
    build[@"buildNumber"] = build_number;
  }
  if (commit_short.length > 0) {
    build[@"commitShort"] = commit_short;
  }
  if (stage.length > 0) {
    build[@"stage"] = stage;
  }
  return build.count > 0 ? build : nil;
}

NSDictionary* xe_current_compat_report_build_info(void) {
  static NSDictionary* build_info = nil;
  static dispatch_once_t once_token;
  dispatch_once(&once_token, ^{
    NSBundle* bundle = [NSBundle mainBundle];
    NSString* app_version =
        xe_string_from_object([bundle objectForInfoDictionaryKey:@"CFBundleShortVersionString"]);
    NSString* build_number =
        xe_string_from_object([bundle objectForInfoDictionaryKey:@"CFBundleVersion"]);
    NSString* compiled_app_version = [NSString stringWithUTF8String:XE_BUILD_VERSION];
    NSString* compiled_build_number = [NSString stringWithUTF8String:XE_BUILD_NUMBER];
    BOOL uses_placeholder_bundle_version =
        (app_version.length == 0 || [app_version isEqualToString:@"1.0"]) &&
        (build_number.length == 0 || [build_number isEqualToString:@"1"]);
    if (uses_placeholder_bundle_version) {
      app_version = compiled_app_version.length > 0 ? compiled_app_version : @"1.0.0";
      build_number = compiled_build_number.length > 0 ? compiled_build_number : @"0";
    } else {
      if (app_version.length == 0) {
        app_version = compiled_app_version.length > 0 ? compiled_app_version : @"1.0.0";
      }
      if (build_number.length == 0) {
        build_number = compiled_build_number.length > 0 ? compiled_build_number : @"0";
      }
    }

    NSString* attested_channel =
        xe_string_from_object([bundle objectForInfoDictionaryKey:@"XeniOSBuildChannel"]);
    NSString* build_stage =
        xe_string_from_object([bundle objectForInfoDictionaryKey:@"XeniOSBuildStage"]);
    NSString* attestation_payload =
        xe_string_from_object([bundle objectForInfoDictionaryKey:@"XeniOSBuildAttestationPayload"]);
    NSString* attestation_signature = xe_string_from_object(
        [bundle objectForInfoDictionaryKey:@"XeniOSBuildAttestationSignature"]);
    BOOL has_attested_channel = [attested_channel isEqualToString:@"release"] ||
                                [attested_channel isEqualToString:@"preview"];
    BOOL has_attestation = attestation_payload.length > 0 && attestation_signature.length > 0;
    NSString* channel = has_attested_channel && has_attestation ? attested_channel : @"self-built";
    BOOL official = has_attested_channel && has_attestation;
    NSString* commit_short = [NSString stringWithUTF8String:XE_BUILD_COMMIT_SHORT];
    NSString* build_id = xe_make_build_id(@"ios", channel, app_version, build_number, build_stage);

    NSMutableDictionary* mutable_build_info = [NSMutableDictionary
        dictionaryWithObjectsAndKeys:build_id, @"buildId", channel, @"channel", @(official),
                                     @"official", app_version, @"appVersion", build_number,
                                     @"buildNumber", commit_short, @"commitShort", nil];
    if (build_stage.length > 0) {
      mutable_build_info[@"stage"] = build_stage;
    }
    if (has_attestation) {
      mutable_build_info[@"attestation"] = @{
        @"payload" : attestation_payload,
        @"signature" : attestation_signature,
      };
    }
    build_info = [mutable_build_info copy];
  });
  return build_info;
}

NSString* xe_discussion_cache_path(uint32_t title_id) {
  NSString* caches =
      NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES).firstObject;
  return [caches
      stringByAppendingPathComponent:[NSString stringWithFormat:@"discussion-%08X.json", title_id]];
}

NSString* xe_compat_cache_path(void) {
  NSString* caches =
      NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES).firstObject;
  return [caches stringByAppendingPathComponent:@"compat-data.json"];
}

NSString* xe_current_iso_date_string(void) {
  static NSDateFormatter* formatter = nil;
  static dispatch_once_t once_token;
  dispatch_once(&once_token, ^{
    formatter = [[NSDateFormatter alloc] init];
    formatter.dateFormat = @"yyyy-MM-dd";
    formatter.locale = [[[NSLocale alloc] initWithLocaleIdentifier:@"en_US_POSIX"] autorelease];
    formatter.timeZone = [NSTimeZone timeZoneForSecondsFromGMT:0];
  });
  return [formatter stringFromDate:[NSDate date]];
}

NSInteger xe_issue_number_from_url(NSString* issue_url) {
  NSURL* url = [NSURL URLWithString:issue_url];
  NSString* last_component = url.pathComponents.lastObject;
  NSInteger issue_number = last_component.integerValue;
  return issue_number > 0 ? issue_number : 0;
}

NSDictionary* xe_build_local_compat_report(NSString* device, NSString* device_machine,
                                           NSString* os_version, NSString* status, NSString* perf,
                                           NSString* notes, NSDictionary* build_info) {
  NSMutableDictionary* report = [NSMutableDictionary
      dictionaryWithObjectsAndKeys:device ?: @"Unknown", @"device", @"ios", @"platform",
                                   os_version ?: @"", @"osVersion", @"arm64", @"arch", @"msl",
                                   @"gpuBackend", status ?: @"nothing", @"status", perf ?: @"n/a",
                                   @"perf", xe_current_iso_date_string(), @"date", notes ?: @"",
                                   @"notes", @"app", @"source", nil];
  if ([device_machine isKindOfClass:[NSString class]] && device_machine.length > 0) {
    report[@"deviceMachine"] = device_machine;
  }
  NSDictionary* sanitized_build = xe_compat_build_info_from_entry(@{@"build" : build_info ?: @{}});
  if (sanitized_build) {
    report[@"build"] = sanitized_build;
  }
  return report;
}

NSDictionary* xe_update_cached_compat_entry_for_submission(uint32_t title_id, NSString* title,
                                                           NSDictionary* report,
                                                           NSString* issue_url) {
  NSString* cache_path = xe_compat_cache_path();
  NSData* cached_data = [NSData dataWithContentsOfFile:cache_path];
  NSMutableArray* entries = [NSMutableArray array];
  if (cached_data.length > 0) {
    id parsed = [NSJSONSerialization JSONObjectWithData:cached_data options:0 error:nil];
    if ([parsed isKindOfClass:[NSArray class]]) {
      [entries addObjectsFromArray:(NSArray*)parsed];
    }
  }

  NSString* title_id_string = [NSString stringWithFormat:@"%08X", title_id];
  NSUInteger existing_index = NSNotFound;
  NSDictionary* current_entry = nil;
  for (NSUInteger i = 0; i < entries.count; ++i) {
    id item = entries[i];
    if (![item isKindOfClass:[NSDictionary class]]) {
      continue;
    }
    NSString* cached_title_id = xe_string_from_object(item[@"titleId"]);
    if ([cached_title_id caseInsensitiveCompare:title_id_string] == NSOrderedSame) {
      existing_index = i;
      current_entry = item;
      break;
    }
  }

  NSMutableArray* reports = [NSMutableArray arrayWithObject:report];
  NSArray* existing_reports =
      [current_entry[@"reports"] isKindOfClass:[NSArray class]] ? current_entry[@"reports"] : nil;
  if (existing_reports) {
    [reports addObjectsFromArray:existing_reports];
  }

  NSMutableDictionary* next_entry =
      current_entry ? [[current_entry mutableCopy] autorelease] : [NSMutableDictionary dictionary];
  next_entry[@"titleId"] = title_id_string;
  next_entry[@"title"] = title ?: title_id_string;
  next_entry[@"status"] = xe_string_from_object(report[@"status"]) ?: @"nothing";
  next_entry[@"perf"] = xe_string_from_object(report[@"perf"]) ?: @"n/a";
  next_entry[@"notes"] = xe_string_from_object(report[@"notes"]) ?: @"";
  next_entry[@"updatedAt"] = xe_string_from_object(report[@"date"]) ?: xe_current_iso_date_string();
  next_entry[@"reports"] = reports;

  NSString* device = xe_string_from_object(report[@"device"]);
  NSString* device_machine = xe_string_from_object(report[@"deviceMachine"]);
  NSString* platform = xe_string_from_object(report[@"platform"]);
  NSString* os_version = xe_string_from_object(report[@"osVersion"]);
  NSString* arch = xe_string_from_object(report[@"arch"]);
  NSString* gpu_backend = xe_string_from_object(report[@"gpuBackend"]);

  if (device.length > 0) next_entry[@"device"] = device;
  if (device_machine.length > 0) next_entry[@"deviceMachine"] = device_machine;
  if (platform.length > 0) next_entry[@"platform"] = platform;
  if (os_version.length > 0) next_entry[@"osVersion"] = os_version;
  if (arch.length > 0) next_entry[@"arch"] = arch;
  if (gpu_backend.length > 0) next_entry[@"gpuBackend"] = gpu_backend;

  NSMutableDictionary* last_report = [NSMutableDictionary dictionary];
  if (device.length > 0) last_report[@"device"] = device;
  if (platform.length > 0) last_report[@"platform"] = platform;
  if (os_version.length > 0) last_report[@"osVersion"] = os_version;
  if (arch.length > 0) last_report[@"arch"] = arch;
  if (gpu_backend.length > 0) last_report[@"gpuBackend"] = gpu_backend;
  if (last_report.count > 0) {
    next_entry[@"lastReport"] = last_report;
  }

  NSMutableArray* platforms =
      [NSMutableArray arrayWithArray:[current_entry[@"platforms"] isKindOfClass:[NSArray class]]
                                         ? current_entry[@"platforms"]
                                         : @[]];
  if (platform.length > 0 && ![platforms containsObject:platform]) {
    [platforms addObject:platform];
  }
  if (platforms.count > 0) {
    next_entry[@"platforms"] = platforms;
  }

  NSString* next_issue_url =
      issue_url.length > 0 ? issue_url : xe_string_from_object(current_entry[@"issueUrl"]);
  if (next_issue_url.length > 0) {
    next_entry[@"issueUrl"] = next_issue_url;
    NSInteger issue_number = xe_issue_number_from_url(next_issue_url);
    if (issue_number > 0) {
      next_entry[@"issueNumber"] = @(issue_number);
    }
  }

  if (existing_index != NSNotFound) {
    entries[existing_index] = next_entry;
  } else {
    [entries addObject:next_entry];
  }

  if ([NSJSONSerialization isValidJSONObject:entries]) {
    NSError* write_error = nil;
    NSData* data = [NSJSONSerialization dataWithJSONObject:entries
                                                   options:NSJSONWritingPrettyPrinted
                                                     error:&write_error];
    if (data && !write_error) {
      NSMutableData* writable = [data mutableCopy];
      static const char newline = '\n';
      [writable appendBytes:&newline length:1];
      [writable writeToFile:cache_path atomically:YES];
      [writable release];
    }
  }
  return next_entry;
}

NSDictionary* xe_cache_discussion_snapshot_for_submission(uint32_t title_id,
                                                          NSDictionary* compat_entry) {
  if (!compat_entry) {
    return nil;
  }

  NSMutableDictionary* snapshot = [NSMutableDictionary dictionary];
  NSArray* reports =
      [compat_entry[@"reports"] isKindOfClass:[NSArray class]] ? compat_entry[@"reports"] : nil;
  if (reports.count > 0) {
    snapshot[@"reports"] = reports;
  }
  NSString* issue_url = xe_string_from_object(compat_entry[@"issueUrl"]);
  if (issue_url.length > 0) {
    snapshot[@"issueUrl"] = issue_url;
    NSInteger issue_number = xe_issue_number_from_url(issue_url);
    if (issue_number > 0) {
      snapshot[@"issueNumber"] = @(issue_number);
    }
  } else if ([compat_entry[@"issueNumber"] isKindOfClass:[NSNumber class]]) {
    snapshot[@"issueNumber"] = compat_entry[@"issueNumber"];
  }

  if (snapshot.count == 0) {
    return nil;
  }

  if ([NSJSONSerialization isValidJSONObject:snapshot]) {
    NSError* write_error = nil;
    NSData* data = [NSJSONSerialization dataWithJSONObject:snapshot
                                                   options:NSJSONWritingPrettyPrinted
                                                     error:&write_error];
    if (data && !write_error) {
      NSMutableData* writable = [data mutableCopy];
      static const char newline = '\n';
      [writable appendBytes:&newline length:1];
      [writable writeToFile:xe_discussion_cache_path(title_id) atomically:YES];
      [writable release];
    }
  }
  return snapshot;
}

NSArray<NSString*>* xe_compat_statuses(void) {
  return @[ @"playable", @"ingame", @"intro", @"loads", @"nothing" ];
}

NSArray<NSString*>* xe_compat_status_labels(void) {
  return @[ @"Playable", @"In-Game", @"Intro", @"Loads", @"Nothing" ];
}

NSArray<NSString*>* xe_compat_perfs(void) { return @[ @"great", @"ok", @"poor", @"n/a" ]; }

NSArray<NSString*>* xe_compat_perf_labels(void) { return @[ @"Great", @"OK", @"Poor", @"N/A" ]; }

CGFloat xe_compat_hero_height_for_width(CGFloat width, UIImage* background_art) {
  CGFloat hero_width = MAX(width, 0.0);
  if (hero_width <= 0.0) {
    return 286.0;
  }
  // When background art is available, derive height from the image aspect
  // ratio so the hero card shows more of the artwork.
  if (background_art && background_art.size.width > 0.0 && background_art.size.height > 0.0) {
    CGFloat image_aspect = background_art.size.width / background_art.size.height;
    CGFloat derived = floor(hero_width / image_aspect);
    return MIN(360.0, MAX(240.0, derived));
  }
  return MIN(360.0, MAX(286.0, floor(hero_width * 0.74)));
}

NSDictionary* xe_parse_compat_json(NSData* data) {
  if (!data || data.length == 0) {
    return nil;
  }
  NSError* error = nil;
  id parsed = [NSJSONSerialization JSONObjectWithData:data options:0 error:&error];
  if (error || ![parsed isKindOfClass:[NSArray class]]) {
    return nil;
  }
  NSMutableDictionary* dict = [NSMutableDictionary dictionaryWithCapacity:[parsed count]];
  for (NSDictionary* game in parsed) {
    if (![game isKindOfClass:[NSDictionary class]]) {
      continue;
    }
    NSString* title_id = game[@"titleId"];
    if ([title_id isKindOfClass:[NSString class]] && title_id.length > 0) {
      [dict setObject:game forKey:[title_id uppercaseString]];
    }
  }
  return dict;
}

NSDictionary* xe_load_cached_compat_data(void) {
  NSData* cached = [NSData dataWithContentsOfFile:xe_compat_cache_path()];
  if (cached.length == 0) {
    return nil;
  }
  return xe_parse_compat_json(cached);
}

NSArray* xe_parse_compat_games_array(NSData* data) {
  if (!data || data.length == 0) {
    return nil;
  }
  id parsed = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
  return [parsed isKindOfClass:[NSArray class]] ? (NSArray*)parsed : nil;
}

NSString* xe_compat_report_identity(NSDictionary* report) {
  if (![report isKindOfClass:[NSDictionary class]]) {
    return nil;
  }
  NSDictionary* build = xe_dictionary_from_object(report[@"build"]);
  return [@[
    xe_string_from_object(report[@"date"]) ?: @"",
    xe_string_from_object(report[@"platform"]) ?: @"",
    xe_string_from_object(report[@"device"]) ?: @"",
    xe_string_from_object(report[@"status"]) ?: @"", xe_string_from_object(report[@"perf"]) ?: @"",
    xe_string_from_object(report[@"notes"]) ?: @"", xe_string_from_object(build[@"buildId"]) ?: @"",
    xe_string_from_object(build[@"buildNumber"]) ?: @"",
    xe_string_from_object(build[@"commitShort"]) ?: @""
  ] componentsJoinedByString:@"|"];
}

NSArray* xe_pending_cached_app_reports(NSDictionary* cached_entry, NSDictionary* remote_entry) {
  NSArray* cached_reports =
      [cached_entry[@"reports"] isKindOfClass:[NSArray class]] ? cached_entry[@"reports"] : nil;
  if (cached_reports.count == 0) {
    return @[];
  }

  NSMutableSet* remote_identities = [NSMutableSet set];
  NSArray* remote_reports =
      [remote_entry[@"reports"] isKindOfClass:[NSArray class]] ? remote_entry[@"reports"] : nil;
  for (id remote_report in remote_reports) {
    NSString* identity = xe_compat_report_identity(remote_report);
    if (identity.length > 0) {
      [remote_identities addObject:identity];
    }
  }

  NSMutableArray* pending_reports = [NSMutableArray array];
  for (id cached_report in cached_reports) {
    if (![cached_report isKindOfClass:[NSDictionary class]]) {
      continue;
    }
    if (![xe_string_from_object(cached_report[@"source"]) isEqualToString:@"app"]) {
      continue;
    }
    NSString* cached_identity = xe_compat_report_identity(cached_report);
    if (cached_identity.length == 0 || [remote_identities containsObject:cached_identity]) {
      continue;
    }
    [pending_reports addObject:cached_report];
  }

  return pending_reports;
}

BOOL xe_cached_entry_has_pending_app_report(NSDictionary* cached_entry,
                                            NSDictionary* remote_entry) {
  return xe_pending_cached_app_reports(cached_entry, remote_entry).count > 0;
}

NSDictionary* xe_merge_remote_compat_entry_with_cached_submission(NSDictionary* remote_entry,
                                                                  NSDictionary* cached_entry) {
  NSMutableDictionary* merged_entry = [[remote_entry mutableCopy] autorelease];

  NSArray* pending_reports = xe_pending_cached_app_reports(cached_entry, remote_entry);
  NSArray* remote_reports =
      [remote_entry[@"reports"] isKindOfClass:[NSArray class]] ? remote_entry[@"reports"] : nil;
  NSMutableArray* merged_reports =
      [NSMutableArray arrayWithCapacity:remote_reports.count + pending_reports.count];
  if (pending_reports.count > 0) {
    [merged_reports addObjectsFromArray:pending_reports];
  }
  if (remote_reports.count > 0) {
    [merged_reports addObjectsFromArray:remote_reports];
  }
  if (merged_reports.count > 0) {
    merged_entry[@"reports"] = merged_reports;
  }

  for (NSString* key in @[
         @"status", @"perf", @"notes", @"updatedAt", @"device", @"deviceMachine", @"platform",
         @"osVersion", @"arch", @"gpuBackend"
       ]) {
    id value = cached_entry[key];
    if ([value isKindOfClass:[NSString class]] && [value length] > 0) {
      merged_entry[key] = value;
    }
  }

  NSDictionary* cached_last_report = xe_dictionary_from_object(cached_entry[@"lastReport"]);
  if (cached_last_report) {
    merged_entry[@"lastReport"] = cached_last_report;
  }

  NSMutableArray* merged_platforms =
      [NSMutableArray arrayWithArray:[remote_entry[@"platforms"] isKindOfClass:[NSArray class]]
                                         ? remote_entry[@"platforms"]
                                         : @[]];
  NSArray* cached_platforms =
      [cached_entry[@"platforms"] isKindOfClass:[NSArray class]] ? cached_entry[@"platforms"] : nil;
  for (id platform in cached_platforms) {
    if ([platform isKindOfClass:[NSString class]] && ![merged_platforms containsObject:platform]) {
      [merged_platforms addObject:platform];
    }
  }
  if (merged_platforms.count > 0) {
    merged_entry[@"platforms"] = merged_platforms;
  }

  NSString* remote_title = xe_string_from_object(remote_entry[@"title"]);
  NSString* cached_title = xe_string_from_object(cached_entry[@"title"]);
  if (remote_title.length == 0 && cached_title.length > 0) {
    merged_entry[@"title"] = cached_title;
  }

  NSString* remote_issue_url = xe_string_from_object(remote_entry[@"issueUrl"]);
  NSString* cached_issue_url = xe_string_from_object(cached_entry[@"issueUrl"]);
  if (remote_issue_url.length == 0 && cached_issue_url.length > 0) {
    merged_entry[@"issueUrl"] = cached_issue_url;
  }
  if (![merged_entry[@"issueNumber"] isKindOfClass:[NSNumber class]] &&
      [cached_entry[@"issueNumber"] isKindOfClass:[NSNumber class]]) {
    merged_entry[@"issueNumber"] = cached_entry[@"issueNumber"];
  }

  return merged_entry;
}

NSArray* xe_merge_remote_compat_games_with_cached_submissions(NSArray* remote_games,
                                                              NSArray* cached_games) {
  if (remote_games.count == 0) {
    return cached_games.count > 0 ? cached_games : remote_games;
  }
  if (cached_games.count == 0) {
    return remote_games;
  }

  NSMutableArray* merged = [NSMutableArray arrayWithArray:remote_games];
  NSMutableDictionary* remote_indexes =
      [NSMutableDictionary dictionaryWithCapacity:remote_games.count];
  for (NSUInteger i = 0; i < remote_games.count; ++i) {
    id item = remote_games[i];
    if (![item isKindOfClass:[NSDictionary class]]) {
      continue;
    }
    NSString* title_id = xe_string_from_object(item[@"titleId"]);
    if (title_id.length > 0) {
      remote_indexes[[title_id uppercaseString]] = @(i);
    }
  }

  for (id item in cached_games) {
    if (![item isKindOfClass:[NSDictionary class]]) {
      continue;
    }
    NSDictionary* cached_entry = (NSDictionary*)item;
    NSString* title_id = [xe_string_from_object(cached_entry[@"titleId"]) uppercaseString];
    if (title_id.length == 0) {
      continue;
    }

    NSNumber* remote_index = remote_indexes[title_id];
    NSDictionary* remote_entry =
        remote_index ? xe_dictionary_from_object(merged[remote_index.unsignedIntegerValue]) : nil;
    if (!remote_entry) {
      if (xe_cached_entry_has_pending_app_report(cached_entry, nil)) {
        [merged addObject:cached_entry];
      }
      continue;
    }

    if (xe_cached_entry_has_pending_app_report(cached_entry, remote_entry)) {
      merged[remote_index.unsignedIntegerValue] =
          xe_merge_remote_compat_entry_with_cached_submission(remote_entry, cached_entry);
    }
  }

  return merged;
}

NSURLSession* xe_compat_url_session(void) {
  static NSURLSession* session = nil;
  static dispatch_once_t once_token;
  dispatch_once(&once_token, ^{
    NSURLSessionConfiguration* config = [NSURLSessionConfiguration defaultSessionConfiguration];
    if (@available(iOS 11.0, *)) {
      config.waitsForConnectivity = YES;
    }
    config.timeoutIntervalForRequest = 20.0;
    config.timeoutIntervalForResource = 45.0;
    session = [[NSURLSession sessionWithConfiguration:config] retain];
  });
  return session;
}
void xe_fetch_compat_data_from_urls(NSArray<NSString*>* url_strings, NSUInteger index,
                                    NSData* cached,
                                    void (^completion)(NSDictionary* _Nullable data)) {
  if (index >= [url_strings count]) {
    return;
  }

  NSURL* url = [NSURL URLWithString:url_strings[index]];
  if (!url) {
    xe_fetch_compat_data_from_urls(url_strings, index + 1, cached, completion);
    return;
  }

  NSURLSessionDataTask* task = [xe_compat_url_session()
        dataTaskWithURL:url
      completionHandler:^(NSData* data, NSURLResponse* response, NSError* error) {
        if (error || data.length == 0) {
          xe_fetch_compat_data_from_urls(url_strings, index + 1, cached, completion);
          return;
        }

        NSHTTPURLResponse* http = (NSHTTPURLResponse*)response;
        if (![http isKindOfClass:[NSHTTPURLResponse class]] || http.statusCode != 200) {
          xe_fetch_compat_data_from_urls(url_strings, index + 1, cached, completion);
          return;
        }

        NSArray* remote_games = xe_parse_compat_games_array(data);
        if (!remote_games) {
          xe_fetch_compat_data_from_urls(url_strings, index + 1, cached, completion);
          return;
        }
        if (remote_games.count == 0) {
          xe_fetch_compat_data_from_urls(url_strings, index + 1, cached, completion);
          return;
        }

        NSArray* cached_games = xe_parse_compat_games_array(cached);
        NSArray* merged_games = cached_games ? xe_merge_remote_compat_games_with_cached_submissions(
                                                   remote_games, cached_games)
                                             : remote_games;
        BOOL preserved_cached_submission = ![merged_games isEqualToArray:remote_games];
        NSData* data_to_store = data;
        if (preserved_cached_submission) {
          NSError* serialize_error = nil;
          NSData* serialized = [NSJSONSerialization dataWithJSONObject:merged_games
                                                               options:NSJSONWritingPrettyPrinted
                                                                 error:&serialize_error];
          if (!serialized || serialize_error) {
            xe_fetch_compat_data_from_urls(url_strings, index + 1, cached, completion);
            return;
          }
          NSMutableData* writable = [serialized mutableCopy];
          static const char newline = '\n';
          [writable appendBytes:&newline length:1];
          data_to_store = [writable autorelease];
        }

        NSDictionary* result = xe_parse_compat_json(data_to_store);
        if (!result) {
          xe_fetch_compat_data_from_urls(url_strings, index + 1, cached, completion);
          return;
        }

        if (cached.length == 0 || ![cached isEqualToData:data_to_store]) {
          [data_to_store writeToFile:xe_compat_cache_path() atomically:YES];
          dispatch_async(dispatch_get_main_queue(), ^{
            if (completion) {
              completion(result);
            }
          });
        }
      }];
  [task resume];
}

void xe_fetch_compat_data(void (^completion)(NSDictionary* _Nullable data)) {
  NSData* cached = [NSData dataWithContentsOfFile:xe_compat_cache_path()];
  if (cached.length > 0) {
    NSDictionary* cached_result = xe_parse_compat_json(cached);
    if (cached_result) {
      dispatch_async(dispatch_get_main_queue(), ^{
        if (completion) {
          completion(cached_result);
        }
      });
    }
  }

  xe_fetch_compat_data_from_urls(
      @[
        @"https://xenios-compat-api.xenios.workers.dev/games",
        // The static site export can lag behind freshly submitted self-built reports,
        // so use it only if the live API is unavailable.
        @"https://xenios.jp/compatibility/data.json",
      ],
      0, cached, completion);
}
